/**
 * Pass 46 Phase 3 — deterministic CHURN analysis (driver tree + win-back).
 *
 * Doctrine: the LLM does NOT compute methodology math. Every number the
 * churn report shows is computed here, deterministically, from clean
 * mission_responses rows. The narrator LLM only writes prose ABOUT the
 * object this module emits.
 *
 * Question metadata contract — generated by CHURN_SURVEY_GEN_SYSTEM in
 * src/services/claudeAI.js (Pass 31 B5), enforced by validateChurnSurvey
 * (claudeAI.js:1767-1788). churn_stage enum (claudeAI.js:1740):
 *   "screener|reason|satisfaction|win_back|switch|warning|tenure"
 * with methodology="churn_driver" on every question.
 *
 * Exact scales / option strings this module keys on (quoted from the
 * generator prompt, 11 fixed questions, claudeAI.js:1748-1758):
 *  - q2  REASON CATEGORY (1749, churn_stage="reason", type="multi") options:
 *        ["Price","Product fit","Customer service","Competition",
 *         "Life change","Quality","Features","Trust","Other"]
 *  - q3  REASON DETAIL  (1750, "reason", type="text") — verbatims source.
 *  - q4  SATISFACTION AT CHURN (1751, "satisfaction", type="single" 5-pt) options:
 *        ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]
 *  - q5  NPS AT CHURN (1752, "satisfaction", type="rating" 0-10).
 *  - q6  WIN-BACK PROBABILITY (1753, "win_back", type="single") options:
 *        ["Yes","Maybe","No"] — the affirmative option is "Yes";
 *        winnable_pct = share answering "Yes". "Maybe" stays visible in
 *        the distribution but is NOT counted as winnable.
 *  - q7  WIN-BACK TRIGGERS (1754, "win_back", type="multi") options:
 *        ["Price discount or promo","New feature or improvement","Better service",
 *         "Personal outreach","New product offering","Change in my situation","Other"]
 *  - q8  COMPETITIVE SWITCH (1755, "switch", type="text") — destination.
 *  - q9  CES AT FINAL INTERACTION (1756, "switch", type="rating" 1-7).
 *  - q10 WARNING SIGNS (1757, "warning", type="text").
 *  - q11 TIME TO CHURN (1758, "tenure", type="single") options:
 *        ["Less than 1 month","1-3 months","3-12 months","1-3 years","More than 3 years"]
 *
 * Contract: computeChurn(rows, questions, mission) → plain JSON.
 * rows = clean mission_responses ({persona_id, question_id, answer}).
 * Incomputable → null, never throw. Deterministic for identical input.
 */

const {
  byQuestion, distribution, ratingStats, round4, personaCount, num,
} = require('./shared');

// ── Local helpers (each Phase 3 module is self-contained; only shared.js
//    primitives are shared) ────────────────────────────────────────────────

/** Normalize for label matching — same convention as passesScreening (simulate.js:142). */
function norm(v) {
  return String(v ?? '').trim().toLowerCase();
}

/** Rows whose answer is a usable scalar (non-empty string / number / boolean). */
function scalarAnswered(rows) {
  return (rows || []).filter((r) => {
    const a = r && r.answer;
    return (typeof a === 'string' && a.trim() !== '') || typeof a === 'number' || typeof a === 'boolean';
  });
}

/** Rows with any non-empty answer (scalar, non-empty array, or object). */
function answered(rows) {
  return (rows || []).filter((r) => {
    const a = r && r.answer;
    if (a === null || a === undefined || a === '') return false;
    if (Array.isArray(a) && a.length === 0) return false;
    return true;
  });
}

/** Free-text verbatims in input-row order; items capped, total stated. */
function collectVerbatims(rows, cap = 30) {
  const items = [];
  let total = 0;
  for (const r of rows || []) {
    const a = r && r.answer;
    if (typeof a === 'string' && a.trim() !== '') {
      total += 1;
      if (items.length < cap) items.push(a.trim());
    }
  }
  return { items, total };
}

/** Section guard: any unexpected shape degrades to null instead of throwing. */
function safe(fn) {
  try { return fn(); } catch (err) { return null; }
}

/**
 * Ranked multi-select shares. Base = RESPONDENTS (personas with ≥1
 * selection — empty arrays / nulls don't count), NOT selections; both
 * bases are stated: n = respondents, selections = total picks. A multi
 * answer that arrives as a bare scalar (simulator drift) counts as one
 * respondent with one selection. Rank: count desc, then label asc
 * (deterministic tie-break).
 */
function rankedMulti(rows) {
  const ans = answered(rows);
  const respondents = ans.length;
  if (respondents === 0) return null;
  const dist = distribution(ans); // arrays count once per selection
  const selections = Object.values(dist).reduce((s, v) => s + v, 0);
  const ranked = Object.entries(dist)
    .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))
    .map(([reason, count]) => ({
      reason,
      count,
      pct_of_respondents: round4((count / respondents) * 100),
    }));
  return { ranked, n: respondents, selections };
}

/** {distribution, n} over scalar answers (labels or free text), or null. */
function scalarDistribution(rows) {
  const ans = scalarAnswered(rows);
  if (ans.length === 0) return null;
  return { distribution: distribution(ans), n: ans.length };
}

// ── Main ───────────────────────────────────────────────────────────────────

/**
 * @param {Array<{persona_id, question_id, answer}>} rows  clean mission_responses
 * @param {Array} questions  mission.questions (falls back to mission.questions)
 * @param {object} mission   full mission row (context / questions fallback)
 * @returns {object} plain-JSON churn analysis (see header)
 */
function computeChurn(rows, questions, mission) {
  const skeleton = {
    methodology: 'churn',
    n: 0,
    drivers: null,
    satisfaction_at_churn: null,
    winback: null,
    winback_triggers: null,
    switching: null,
    ces_at_exit: null,
    warning_signs: null,
    tenure: null,
    reason_verbatims: [],
  };
  try {
    const allRows = Array.isArray(rows) ? rows : [];
    const qs = Array.isArray(questions)
      ? questions
      : (Array.isArray(mission?.questions) ? mission.questions : []);
    const byQ = byQuestion(allRows);
    const rowsFor = (q) => (q ? (byQ.get(q.id) || []) : []);
    const stage = (s) => qs.filter((q) => q && q.churn_stage === s);

    // ── reason stage: q2 multi = driver categories, q3 text = detail ──────
    const reasonQs = stage('reason');
    const reasonMulti = reasonQs.find((q) => q.type === 'multi') || null;
    const reasonText = reasonQs.find((q) => q.type === 'text') || null;

    // Ranked driver shares. Base = respondents, not selections (both stated).
    const drivers = safe(() => (reasonMulti ? rankedMulti(rowsFor(reasonMulti)) : null));
    const reasonVerbatims = safe(() => (reasonText ? collectVerbatims(rowsFor(reasonText)).items : [])) || [];

    // ── satisfaction stage: q4 single 5-pt + q5 NPS 0-10 ──────────────────
    // Spec bullet: "satisfaction at churn: distribution + ratingStats if
    // numeric-ish" — emitted per question (the stage hosts both a labeled
    // 5-pt single and a 0-10 rating, claudeAI.js:1751-1752). stats comes
    // from ratingStats over num()-coercible answers; for the labeled
    // single it is naturally null. No range filter here because the stage
    // is heterogeneous (documented choice).
    const satisfactionAtChurn = safe(() => {
      const entries = stage('satisfaction')
        .map((q) => {
          const ans = answered(rowsFor(q));
          return {
            question_id: q.id,
            text: q.text || '',
            distribution: ans.length ? distribution(ans) : null,
            stats: ratingStats(ans), // null unless numeric-ish
            n: ans.length,
          };
        })
        .filter((e) => e.n > 0); // zero-answer questions are incomputable → dropped
      return entries.length ? entries : null;
    });

    // ── win_back stage: q6 single Yes/Maybe/No + q7 multi triggers ────────
    const wbQs = stage('win_back');
    const wbSingle = wbQs.find((q) => q.type === 'single') || null;
    const wbMulti = wbQs.find((q) => q.type === 'multi') || null;

    // winnable_pct = share of the affirmative option "Yes" (claudeAI.js:1753
    // options ["Yes","Maybe","No"]); matched normalized. Base n = scalar answers.
    const winback = safe(() => {
      const ans = scalarAnswered(rowsFor(wbSingle));
      if (ans.length === 0) return null;
      const yes = ans.filter((r) => norm(r.answer) === 'yes').length;
      return {
        winnable_pct: round4((yes / ans.length) * 100),
        n: ans.length,
        distribution: distribution(ans),
      };
    });
    // Pass 46 addition beyond the minimum emit shape: q7 triggers — the
    // win-back playbook chart needs a deterministic source.
    const winbackTriggers = safe(() => (wbMulti ? rankedMulti(rowsFor(wbMulti)) : null));

    // ── switch stage: q8 text destination + q9 CES rating 1-7 ─────────────
    const swQs = stage('switch');
    const swText = swQs.find((q) => q.type === 'text') || null;
    const swRating = swQs.find((q) => q.type === 'rating') || null;

    // Destination distribution = exact-string counts of the free-text
    // competitor answers (claudeAI.js:1755).
    const switching = safe(() => (swText ? scalarDistribution(rowsFor(swText)) : null));
    // Pass 46 addition: CES at final interaction (claudeAI.js:1756, 1-7).
    const cesAtExit = safe(() => {
      const vals = rowsFor(swRating)
        .map((r) => num(r.answer))
        .filter((v) => v !== null && v >= 1 && v <= 7);
      return vals.length ? ratingStats(vals.map((v) => ({ answer: v }))) : null;
    });

    // ── warning + tenure stages: distributions ─────────────────────────────
    const warningQ = stage('warning')[0] || null;
    const tenureQ = stage('tenure')[0] || null;

    return {
      ...skeleton,
      n: personaCount(allRows),
      drivers,
      satisfaction_at_churn: satisfactionAtChurn,
      winback,
      winback_triggers: winbackTriggers,
      switching,
      ces_at_exit: cesAtExit,
      warning_signs: safe(() => (warningQ ? scalarDistribution(rowsFor(warningQ)) : null)),
      tenure: safe(() => (tenureQ ? scalarDistribution(rowsFor(tenureQ)) : null)),
      reason_verbatims: reasonVerbatims, // ≤30, input-row order
    };
  } catch (err) {
    // Contract: never throw — degrade to the all-null skeleton.
    return skeleton;
  }
}

module.exports = { computeChurn };
