/**
 * Pass 46 Phase 3 — deterministic SATISFACTION analysis (NPS + CSAT + CES
 * + attribute matrix + retention + driver verbatims).
 *
 * Doctrine: the LLM does NOT compute methodology math. Every number the
 * satisfaction report shows is computed here, deterministically, from
 * clean mission_responses rows. The narrator LLM only writes prose ABOUT
 * the object this module emits.
 *
 * Question metadata contract — generated by CSAT_SURVEY_GEN_SYSTEM in
 * src/services/claudeAI.js (Pass 29 B8), enforced by validateCSATSurvey
 * (claudeAI.js:930-952). methodology enum (claudeAI.js:885):
 *   "screener|nps|nps_driver|csat|csat_driver|ces|ces_driver|
 *    attribute_matrix|retention|specific_issues", plus "is_driver": true
 * on the three driver questions.
 *
 * Exact scales / option strings this module keys on (quoted from the
 * generator prompt):
 *  - q2  NPS        (claudeAI.js:901) — type="rating", "0-10 scale".
 *  - q4  CSAT       (claudeAI.js:903) — type="single", options:
 *        ["Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied"]
 *        → top-2-box = "Satisfied" + "Very satisfied".
 *  - q6  CES        (claudeAI.js:905) — type="rating", "7-point scale
 *        (1=Very difficult, 7=Very easy)" → top-2-box = 6 + 7.
 *  - q8  attributes (claudeAI.js:907) — "Single rating Q with options=[]
 *        (1-5 scale); the options list each attribute as a sub-row (the
 *        simulator will iterate). Set 'options' to
 *        ["Quality","Value","Reliability","Customer service","Ease of use"]."
 *  - q9  retention  (claudeAI.js:908) — type="rating", "1-5 scale".
 *  - q10 issues     (claudeAI.js:909) — type="multi", 5-7 brief-specific options.
 *
 * Contract: computeSatisfaction(rows, questions, mission) → plain JSON.
 * rows = clean mission_responses ({persona_id, question_id, answer}).
 * Incomputable → null, never throw. Deterministic for identical input.
 */

const {
  byQuestion, distribution, ratingStats, round4, personaCount, num,
} = require('./shared');

// ── Local helpers (each Phase 3 module is self-contained; only shared.js
//    primitives are shared) ────────────────────────────────────────────────

/** Normalize for label matching — same convention as passesScreening (simulate.js:142). */
function norm(v) {
  return String(v ?? '').trim().toLowerCase();
}

/** Rows whose answer is a usable scalar (non-empty string / number / boolean). */
function scalarAnswered(rows) {
  return (rows || []).filter((r) => {
    const a = r && r.answer;
    return (typeof a === 'string' && a.trim() !== '') || typeof a === 'number' || typeof a === 'boolean';
  });
}

/** Rows with any non-empty answer (scalar, non-empty array, or object). */
function answered(rows) {
  return (rows || []).filter((r) => {
    const a = r && r.answer;
    if (a === null || a === undefined || a === '') return false;
    if (Array.isArray(a) && a.length === 0) return false;
    return true;
  });
}

/**
 * Free-text verbatims in input-row order. items capped (default 30 per the
 * Phase 3 contract); total states how many existed so the cap is honest.
 */
function collectVerbatims(rows, cap = 30) {
  const items = [];
  let total = 0;
  for (const r of rows || []) {
    const a = r && r.answer;
    if (typeof a === 'string' && a.trim() !== '') {
      total += 1;
      if (items.length < cap) items.push(a.trim());
    }
  }
  return { items, total };
}

/** Section guard: any unexpected shape degrades to null instead of throwing. */
function safe(fn) {
  try { return fn(); } catch (err) { return null; }
}

// ── NPS ────────────────────────────────────────────────────────────────────

/**
 * NPS from the methodology="nps" question (0-10 rating, claudeAI.js:901).
 * Promoters 9-10, passives 7-8, detractors 0-6.
 * nps = Math.round((promoters − detractors) / n × 100).
 * Base n = answers that coerce to a number in [0,10]; out-of-range / junk
 * answers are excluded from base and segments (documented honesty rule).
 */
function computeNps(rows) {
  const vals = (rows || []).map((r) => num(r.answer)).filter((v) => v !== null && v >= 0 && v <= 10);
  const n = vals.length;
  if (n === 0) return null;
  let promoters = 0;
  let passives = 0;
  let detractors = 0;
  for (const v of vals) {
    if (v >= 9) promoters += 1;
    else if (v >= 7) passives += 1;
    else detractors += 1;
  }
  const pct = (c) => round4((c / n) * 100);
  return {
    score: Math.round(((promoters - detractors) / n) * 100),
    n, // base for score and all segment pcts
    segments: {
      promoters:  { count: promoters,  pct: pct(promoters) },
      passives:   { count: passives,   pct: pct(passives) },
      detractors: { count: detractors, pct: pct(detractors) },
    },
  };
}

// ── Top-2-box over labeled single-choice options ───────────────────────────

/**
 * Top-2-box share for a "single" question. top2Labels are matched
 * normalized (trim + lowercase). Base n = rows with a scalar answer;
 * off-scale labels stay in the base (and in the distribution) but never
 * count as top-2 — conservative by construction.
 */
function top2Single(rows, top2Labels) {
  const ans = scalarAnswered(rows);
  const n = ans.length;
  if (n === 0) return null;
  const top2Set = new Set(top2Labels.map(norm));
  const top2 = ans.filter((r) => top2Set.has(norm(r.answer))).length;
  return { top2_pct: round4((top2 / n) * 100), n, distribution: distribution(ans) };
}

// ── CES ────────────────────────────────────────────────────────────────────

/**
 * CES top-2-box = 6 + 7 of the 7-point scale (claudeAI.js:905 —
 * "1=Very difficult, 7=Very easy"). Handles numeric AND numeric-string
 * answers (7 and "7") via num(). Base n = answers coercing into [1,7];
 * the distribution is built from the same coerced values so base and
 * distribution always agree.
 */
function computeCes(rows) {
  const vals = (rows || []).map((r) => num(r.answer)).filter((v) => v !== null && v >= 1 && v <= 7);
  const n = vals.length;
  if (n === 0) return null;
  const top2 = vals.filter((v) => v >= 6).length;
  const dist = {};
  for (const v of vals) {
    const k = String(v);
    dist[k] = (dist[k] || 0) + 1;
  }
  return { top2_pct: round4((top2 / n) * 100), n, distribution: dist };
}

// ── Attribute matrix ───────────────────────────────────────────────────────

/**
 * Per-attribute ratingStats for the methodology="attribute_matrix"
 * question(s). The generator prompt (claudeAI.js:907) specifies ONE
 * rating question whose options list the attributes
 * ["Quality","Value","Reliability","Customer service","Ease of use"]
 * as sub-rows, "the simulator will iterate" — i.e. per-attribute
 * sub-answers inside one answer. Three shapes are handled, in order:
 *
 *  1. Sub-answer object (the prompt's intent): answer = {"Quality": 4, ...}.
 *     Keys matched against the question's option labels, normalized.
 *  2. One question PER attribute (generator drift tolerated): several
 *     methodology="attribute_matrix" questions → label from the single
 *     option, else the question text.
 *  3. Plain numeric answers only (what simulate.js:49 — "rating → a whole
 *     number" — actually produces today): a per-attribute split is
 *     incomputable, so we emit a single honest [{label:'Overall', stats}]
 *     instead of fabricating per-attribute numbers.
 *
 * Sub-ratings outside the prompt's 1-5 scale are excluded.
 */
function computeAttributes(amQuestions, byQ) {
  if (!amQuestions.length) return null;

  if (amQuestions.length > 1) {
    // Shape 2 — one question per attribute.
    const out = amQuestions.map((q) => ({
      label: (Array.isArray(q.options) && q.options.length === 1) ? q.options[0] : (q.text || q.id),
      stats: ratingStats(answered(byQ.get(q.id) || [])),
    }));
    return out.some((a) => a.stats) ? out : null;
  }

  const q = amQuestions[0];
  const rows = byQ.get(q.id) || [];
  const labels = (Array.isArray(q.options) && q.options.length) ? q.options : null;

  if (labels) {
    // Shape 1 — per-attribute sub-answer objects.
    const out = labels.map((label) => {
      const key = norm(label);
      const subRows = [];
      for (const r of rows) {
        const a = r && r.answer;
        if (a && typeof a === 'object' && !Array.isArray(a)) {
          for (const [k, v] of Object.entries(a)) {
            if (norm(k) === key) {
              const nv = num(v);
              if (nv !== null && nv >= 1 && nv <= 5) subRows.push({ answer: nv }); // 1-5 scale, claudeAI.js:907
              break;
            }
          }
        }
      }
      return { label, stats: ratingStats(subRows) };
    });
    if (out.some((a) => a.stats)) return out;
  }

  // Shape 3 — numeric-only answers: split unavailable, report overall only.
  const numericRows = rows
    .map((r) => num(r.answer))
    .filter((v) => v !== null && v >= 1 && v <= 5)
    .map((v) => ({ answer: v }));
  const overall = ratingStats(numericRows);
  return overall ? [{ label: 'Overall', stats: overall }] : null;
}

// ── Multi-select ranking (specific_issues) ─────────────────────────────────

/**
 * Ranked option shares for the methodology="specific_issues" multi
 * question (claudeAI.js:909). Base = RESPONDENTS (personas with ≥1
 * selection), not selections; both bases are stated (n + selections).
 * Rank: count desc, then label asc (deterministic tie-break).
 */
function rankedIssues(rows) {
  const ans = answered(rows);
  const respondents = ans.length;
  if (respondents === 0) return null;
  const dist = distribution(ans); // multi arrays count once per selection
  const selections = Object.values(dist).reduce((s, v) => s + v, 0);
  const ranked = Object.entries(dist)
    .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))
    .map(([option, count]) => ({
      option,
      count,
      pct_of_respondents: round4((count / respondents) * 100),
    }));
  return { ranked, n: respondents, selections };
}

// ── Main ───────────────────────────────────────────────────────────────────

/**
 * @param {Array<{persona_id, question_id, answer}>} rows  clean mission_responses
 * @param {Array} questions  mission.questions (falls back to mission.questions)
 * @param {object} mission   full mission row (context / questions fallback)
 * @returns {object} plain-JSON satisfaction analysis (see header)
 */
function computeSatisfaction(rows, questions, mission) {
  const skeleton = {
    methodology: 'satisfaction',
    n: 0,
    nps: null,
    csat: null,
    ces: null,
    attributes: null,
    retention: null,
    issues: null,
    drivers: [],
  };
  try {
    const allRows = Array.isArray(rows) ? rows : [];
    const qs = Array.isArray(questions)
      ? questions
      : (Array.isArray(mission?.questions) ? mission.questions : []);
    const byQ = byQuestion(allRows);
    const rowsFor = (q) => (q ? (byQ.get(q.id) || []) : []);
    // First question per methodology tag (the generator emits exactly one each).
    const qBy = (m) => qs.find((q) => q && q.methodology === m) || null;

    // q4 CSAT top-2-box — exact labels from claudeAI.js:903.
    const CSAT_TOP2 = ['Satisfied', 'Very satisfied'];

    const npsQ = qBy('nps');
    const csatQ = qBy('csat');
    const cesQ = qBy('ces');
    const retentionQ = qBy('retention');
    const issuesQ = qBy('specific_issues');
    const amQs = qs.filter((q) => q && q.methodology === 'attribute_matrix');

    // Retention (claudeAI.js:908 — rating 1-5): ratingStats + distribution.
    const retention = safe(() => {
      const ans = scalarAnswered(rowsFor(retentionQ));
      const vals = ans.map((r) => num(r.answer)).filter((v) => v !== null && v >= 1 && v <= 5);
      if (vals.length === 0) return null;
      const valRows = vals.map((v) => ({ answer: v }));
      const dist = {};
      for (const v of vals) {
        const k = String(v);
        dist[k] = (dist[k] || 0) + 1;
      }
      return { stats: ratingStats(valRows), distribution: dist, n: vals.length };
    });

    // Drivers: every question flagged is_driver=true OR methodology
    // ending in "_driver" (nps_driver / csat_driver / ces_driver,
    // claudeAI.js:902/904/906). ≤30 verbatims each, input-row order.
    const drivers = qs
      .filter((q) => q && (q.is_driver === true || /_driver$/.test(String(q.methodology || ''))))
      .map((q) => {
        const v = collectVerbatims(rowsFor(q));
        return { kind: q.methodology || 'driver', question_id: q.id, n: v.total, verbatims: v.items };
      });

    return {
      ...skeleton,
      n: personaCount(allRows),
      nps: safe(() => computeNps(rowsFor(npsQ))),
      csat: safe(() => top2Single(rowsFor(csatQ), CSAT_TOP2)),
      ces: safe(() => computeCes(rowsFor(cesQ))),
      attributes: safe(() => computeAttributes(amQs, byQ)),
      retention,
      // Pass 46 addition beyond the minimum emit shape: specific_issues
      // (q10) ranked shares — without this the issues chart would have
      // no deterministic source.
      issues: safe(() => rankedIssues(rowsFor(issuesQ))),
      drivers,
    };
  } catch (err) {
    // Contract: never throw — degrade to the all-null skeleton.
    return skeleton;
  }
}

module.exports = { computeSatisfaction };
