/**
 * Pass 46 Phase 3 — deterministic VALIDATE (concept test) analysis.
 *
 * Doctrine: the LLM does NOT compute methodology math. Every number the
 * concept-test report shows is computed here, deterministically, from
 * clean mission_responses rows. The narrator LLM only writes prose ABOUT
 * the object this module emits.
 *
 * Question metadata contract — generated by VALIDATE_SURVEY_GEN_SYSTEM in
 * src/services/claudeAI.js (Pass 30 B1), enforced by validateValidateSurvey
 * (claudeAI.js:1077-1099). funnel_stage enum (claudeAI.js:1046):
 *   "screener|reaction|relevance|uniqueness|believability|intent|
 *    qualitative|price_fairness"
 * with methodology="concept_test" on every question.
 *
 * Exact scales / option strings this module keys on (quoted from the
 * generator prompt, claudeAI.js:1060-1069):
 *  - q2 REACTION      (1061, funnel_stage="reaction")      type="rating" 1-10.
 *  - q3 RELEVANCE     (1062, funnel_stage="relevance")     type="rating" 1-7.
 *  - q4 UNIQUENESS    (1063, funnel_stage="uniqueness")    type="rating" 1-7.
 *  - q5 BELIEVABILITY (1064, funnel_stage="believability") type="rating" 1-7.
 *  - q6 PURCHASE INTENT (1065, funnel_stage="intent") type="single", options:
 *       ["Definitely would buy","Probably would buy","Might or might not",
 *        "Probably would NOT buy","Definitely would NOT buy"]
 *       → top-2-box = "Definitely would buy" + "Probably would buy"
 *       (the two strongest purchase-intent options).
 *  - q7-q9 QUALITATIVE (1066-1068, funnel_stage="qualitative") type="text".
 *  - q10 PRICE FAIR (1069, funnel_stage="price_fairness", only when a
 *        concept_price was supplied) type="single", options:
 *        ["Too low","Fair","Too high"].
 *
 * norms: ALWAYS null — there is no benchmark database yet, and the
 * doctrine forbids inventing one. The renderer must label scores as
 * unbenchmarked when norms === null.
 *
 * Contract: computeValidate(rows, questions, mission) → plain JSON.
 * rows = clean mission_responses ({persona_id, question_id, answer}).
 * Incomputable → null, never throw. Deterministic for identical input.
 */

const {
  byQuestion, distribution, ratingStats, round4, personaCount, num, isSkip,
} = require('./shared');

// ── Local helpers (each Phase 3 module is self-contained; only shared.js
//    primitives are shared) ────────────────────────────────────────────────

/** Normalize for label matching — same convention as passesScreening (simulate.js:142). */
function norm(v) {
  return String(v ?? '').trim().toLowerCase();
}

/** Rows whose answer is a usable scalar (non-empty string / number / boolean). */
function scalarAnswered(rows) {
  return (rows || []).filter((r) => {
    const a = r && r.answer;
    return !isSkip(a) && ((typeof a === 'string' && a.trim() !== '') || typeof a === 'number' || typeof a === 'boolean');
  });
}

/** Free-text verbatims in input-row order; items capped, total stated. */
function collectVerbatims(rows, cap = 30) {
  const items = [];
  let total = 0;
  for (const r of rows || []) {
    const a = r && r.answer;
    if (typeof a === 'string' && a.trim() !== '') {
      total += 1;
      if (items.length < cap) items.push(a.trim());
    }
  }
  return { items, total };
}

/** Section guard: any unexpected shape degrades to null instead of throwing. */
function safe(fn) {
  try { return fn(); } catch (err) { return null; }
}

/**
 * ratingStats over answers coercing into [lo, hi] — the prompt pins each
 * stage's scale (reaction 1-10, the three diagnostics 1-7), so values
 * outside it are junk and excluded. Handles numeric and numeric-string
 * answers via num().
 */
function stageStats(rows, lo, hi) {
  const vals = (rows || [])
    .map((r) => num(r.answer))
    .filter((v) => v !== null && v >= lo && v <= hi);
  if (vals.length === 0) return null;
  return ratingStats(vals.map((v) => ({ answer: v })));
}

// ── Main ───────────────────────────────────────────────────────────────────

/**
 * @param {Array<{persona_id, question_id, answer}>} rows  clean mission_responses
 * @param {Array} questions  mission.questions (falls back to mission.questions)
 * @param {object} mission   full mission row (context / questions fallback)
 * @returns {object} plain-JSON concept-test analysis (see header)
 */
function computeValidate(rows, questions, mission) {
  const skeleton = {
    methodology: 'validate',
    n: 0,
    scores: { reaction: null, relevance: null, uniqueness: null, believability: null },
    intent: null,
    price_fairness: null,
    verbatims: {},
    norms: null, // no benchmark DB yet — explicitly null so the renderer labels honestly
  };
  try {
    const allRows = Array.isArray(rows) ? rows : [];
    const qs = Array.isArray(questions)
      ? questions
      : (Array.isArray(mission?.questions) ? mission.questions : []);
    const byQ = byQuestion(allRows);
    const rowsFor = (q) => (q ? (byQ.get(q.id) || []) : []);
    // First question per funnel_stage (the generator emits one each except
    // qualitative, which has three).
    const stageQ = (s) => qs.find((q) => q && q.funnel_stage === s) || null;

    // Stage scores — scales pinned by the prompt (claudeAI.js:1061-1064).
    const scores = {
      reaction:      safe(() => stageStats(rowsFor(stageQ('reaction')), 1, 10)),
      relevance:     safe(() => stageStats(rowsFor(stageQ('relevance')), 1, 7)),
      uniqueness:    safe(() => stageStats(rowsFor(stageQ('uniqueness')), 1, 7)),
      believability: safe(() => stageStats(rowsFor(stageQ('believability')), 1, 7)),
    };

    // Intent top-2-box — exact labels from claudeAI.js:1065, matched
    // normalized. Base n = scalar answers; off-scale labels stay in the
    // base (and the distribution) but never count as top-2.
    const INTENT_TOP2 = ['Definitely would buy', 'Probably would buy'];
    const intent = safe(() => {
      const ans = scalarAnswered(rowsFor(stageQ('intent')));
      if (ans.length === 0) return null;
      const top2Set = new Set(INTENT_TOP2.map(norm));
      const top2 = ans.filter((r) => top2Set.has(norm(r.answer))).length;
      return {
        top2_pct: round4((top2 / ans.length) * 100),
        n: ans.length,
        distribution: distribution(ans),
      };
    });

    // Price fairness (claudeAI.js:1069 — only present when a price was
    // supplied): distribution over ["Too low","Fair","Too high"].
    const priceFairness = safe(() => {
      const ans = scalarAnswered(rowsFor(stageQ('price_fairness')));
      if (ans.length === 0) return null;
      return { distribution: distribution(ans), n: ans.length };
    });

    // Qualitative verbatims — ≤30 per open question (claudeAI.js:1066-1068),
    // keyed by question_id in questions order; n = total available so the
    // cap is honest.
    const verbatims = {};
    for (const q of qs) {
      if (!q || q.funnel_stage !== 'qualitative') continue;
      const v = safe(() => collectVerbatims(rowsFor(q)));
      if (v) verbatims[q.id] = { question: q.text || '', n: v.total, items: v.items };
    }

    return {
      ...skeleton,
      n: personaCount(allRows),
      scores,
      intent,
      price_fairness: priceFairness,
      verbatims,
      norms: null,
    };
  } catch (err) {
    // Contract: never throw — degrade to the all-null skeleton.
    return skeleton;
  }
}

module.exports = { computeValidate };
