/**
 * VETT — PDF export using pdfkit.
 * Dark-theme styling matching the prototype:
 *   - Deep near-black background (#0B0C15)
 *   - Lime accents (#BEF264)
 *   - Inter for headlines, Manrope/system for body
 *
 * pdfkit ships with Helvetica, so we use Helvetica-Bold for headlines
 * to keep the dependency footprint small (no font files needed).
 */

const PDFDocument = require('pdfkit');
const { BRAND } = require('./shared');

function fillPageBg(doc, color = BRAND.bg) {
  doc.save();
  doc.rect(0, 0, doc.page.width, doc.page.height).fill(color);
  doc.restore();
}

function sectionDivider(doc) {
  doc.moveTo(50, doc.y + 6).lineTo(doc.page.width - 50, doc.y + 6)
     .strokeColor(BRAND.lime).lineWidth(2).stroke();
  doc.moveDown(0.8);
}

function barRow(doc, label, count, pct) {
  const x = 50;
  const y = doc.y;
  const barX = x + 180;
  const barMaxW = doc.page.width - barX - 100;
  const barW = Math.max(2, Math.round((pct / 100) * barMaxW));

  doc.fontSize(10).fillColor(BRAND.text1)
     .text(label.toString().slice(0, 30), x, y, { width: 170, ellipsis: true });

  // Track
  doc.rect(barX, y + 3, barMaxW, 8).fill(BRAND.bg3);
  // Fill
  doc.rect(barX, y + 3, barW, 8).fill(BRAND.lime);

  doc.fontSize(10).fillColor(BRAND.text2)
     .text(`${count}  ·  ${pct}%`, barX + barMaxW + 8, y, { width: 80 });

  doc.moveDown(1.1);
}

function statCard(doc, x, y, w, h, label, value, trendColor = BRAND.lime) {
  doc.roundedRect(x, y, w, h, 10).fill(BRAND.bg2);
  doc.fontSize(9).fillColor(BRAND.text3).text(label.toUpperCase(), x + 14, y + 12, { width: w - 28 });
  doc.fontSize(22).fillColor(trendColor).font('Helvetica-Bold')
     .text(value, x + 14, y + 30, { width: w - 28 });
  doc.font('Helvetica');
}

function buildPDF(pack, res) {
  const { mission, insights, aggregatedByQuestion } = pack;

  const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition',
    `attachment; filename="vett-report-${(mission.title || mission.id).toString().slice(0, 40).replace(/[^a-z0-9]+/gi, '-')}.pdf"`);
  doc.pipe(res);

  // ── COVER PAGE ──────────────────────────────────────────
  fillPageBg(doc);

  // Top glow
  doc.save();
  doc.rect(0, 0, doc.page.width, 8).fill(BRAND.lime);
  doc.restore();

  // VETT wordmark
  doc.fontSize(48).fillColor(BRAND.lime).font('Helvetica-Bold')
     .text('VETT', 50, 80);

  doc.fontSize(12).fillColor(BRAND.text2).font('Helvetica')
     .text('AI-POWERED MARKET RESEARCH', 50, 140);

  // Title
  doc.fontSize(28).fillColor('#ffffff').font('Helvetica-Bold')
     .text(mission.title || 'Research Report', 50, 240, { width: doc.page.width - 100 });

  doc.fontSize(12).fillColor(BRAND.text2).font('Helvetica')
     .text(mission.brief || mission.mission_statement || '', 50, doc.y + 10, {
       width: doc.page.width - 100,
     });

  // Meta strip
  doc.font('Helvetica');
  const metaY = 480;
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.fontSize(10).fillColor(BRAND.text3)
     .text(`Respondents: ${mission.respondent_count || '—'}`, 50, metaY);
  doc.text(`Report generated: ${now}`, 50, metaY + 16);
  doc.text(`Mission ID: ${mission.id}`, 50, metaY + 32);

  // Footer on cover
  doc.fontSize(9).fillColor(BRAND.text3)
     .text('Generated by VETT · vettit.ai', 50, doc.page.height - 40, {
       align: 'center',
       width: doc.page.width - 100,
     });

  // ── EXECUTIVE SUMMARY ───────────────────────────────────
  doc.addPage();
  fillPageBg(doc);

  doc.fontSize(10).fillColor(BRAND.lime).font('Helvetica-Bold')
     .text('01 · EXECUTIVE SUMMARY', 50, 60);
  sectionDivider(doc);

  doc.fontSize(12).fillColor(BRAND.text1).font('Helvetica')
     .text(insights.executive_summary || 'Executive summary unavailable.',
       { lineGap: 5, width: doc.page.width - 100 });
  doc.moveDown(2);

  // KPI cards grid
  if (Array.isArray(insights.kpis) && insights.kpis.length > 0) {
    doc.fontSize(10).fillColor(BRAND.lime).font('Helvetica-Bold').text('HEADLINE KPIs');
    doc.moveDown(0.5);
    const cardW = (doc.page.width - 100 - 20) / 3;
    const cardH = 70;
    const startY = doc.y;
    insights.kpis.slice(0, 3).forEach((kpi, i) => {
      const x = 50 + i * (cardW + 10);
      const trendColor = kpi.trend === 'negative' ? BRAND.red : kpi.trend === 'neutral' ? BRAND.text1 : BRAND.lime;
      statCard(doc, x, startY, cardW, cardH, kpi.label || 'KPI', kpi.value || '—', trendColor);
    });
    doc.y = startY + cardH + 20;
  }

  // ── PER-QUESTION RESULTS ────────────────────────────────
  (mission.questions || []).forEach((q, qi) => {
    if (doc.y > doc.page.height - 200) {
      doc.addPage(); fillPageBg(doc);
    }
    const qAgg = aggregatedByQuestion[q.id] || {};

    doc.fontSize(10).fillColor(BRAND.lime).font('Helvetica-Bold')
       .text(`${String(qi + 2).padStart(2, '0')} · QUESTION ${qi + 1}`);
    sectionDivider(doc);

    doc.fontSize(13).fillColor('#ffffff').font('Helvetica-Bold')
       .text(q.text, { width: doc.page.width - 100 });
    doc.moveDown(0.8);

    if (q.type === 'text') {
      doc.fontSize(10).fillColor(BRAND.text3).text('Sample verbatims:');
      doc.moveDown(0.3);
      (qAgg.verbatims || []).slice(0, 5).forEach(v => {
        doc.fontSize(10).fillColor(BRAND.text2).font('Helvetica-Oblique')
           .text(`“${String(v).slice(0, 200)}”`, { indent: 16, width: doc.page.width - 116, lineGap: 3 });
        doc.moveDown(0.3);
      });
      doc.font('Helvetica');
    } else if (q.type === 'rating') {
      doc.fontSize(11).fillColor(BRAND.lime)
         .text(`Average: ${qAgg.average || 0} / 5  ·  n=${qAgg.n || 0}`);
      doc.moveDown(0.5);
      const dist = qAgg.distribution || {};
      const total = Object.values(dist).reduce((s, v) => s + v, 0) || 1;
      for (let r = 5; r >= 1; r--) {
        const c = dist[r] || 0;
        barRow(doc, `★ ${r}`, c, Math.round((c / total) * 100));
      }
    } else {
      const dist = qAgg.distribution || {};
      const total = Object.values(dist).reduce((s, v) => s + v, 0) || 1;
      Object.entries(dist)
        .sort((a, b) => b[1] - a[1])
        .forEach(([opt, count]) => {
          const pct = Math.round((count / total) * 100);
          barRow(doc, opt, count, pct);
        });
    }

    // Insight pullquote
    const qInsight = (insights.per_question_insights || []).find(pi => pi.question_id === q.id);
    if (qInsight?.headline) {
      doc.moveDown(0.4);
      const boxY = doc.y;
      const boxH = 58;
      doc.roundedRect(50, boxY, doc.page.width - 100, boxH, 6).fill(BRAND.bg2);
      doc.save();
      doc.rect(50, boxY, 3, boxH).fill(BRAND.lime);
      doc.restore();
      doc.fontSize(9).fillColor(BRAND.lime).font('Helvetica-Bold')
         .text('INSIGHT', 64, boxY + 10);
      doc.fontSize(11).fillColor('#ffffff').font('Helvetica-Bold')
         .text(qInsight.headline, 64, boxY + 22, { width: doc.page.width - 128 });
      doc.font('Helvetica').fontSize(9).fillColor(BRAND.text2)
         .text(qInsight.body || '', 64, boxY + 38, { width: doc.page.width - 128 });
      doc.y = boxY + boxH + 10;
    }

    doc.moveDown(1);
  });

  // ── RECOMMENDATIONS ─────────────────────────────────────
  if (Array.isArray(insights.recommendations) && insights.recommendations.length) {
    doc.addPage(); fillPageBg(doc);
    doc.fontSize(10).fillColor(BRAND.lime).font('Helvetica-Bold').text('· RECOMMENDATIONS');
    sectionDivider(doc);
    insights.recommendations.forEach((r, i) => {
      doc.fontSize(11).fillColor(BRAND.lime).font('Helvetica-Bold')
         .text(`${String(i + 1).padStart(2, '0')}.`, 50, doc.y, { continued: true });
      doc.fontSize(11).fillColor(BRAND.text1).font('Helvetica')
         .text(`  ${r}`, { width: doc.page.width - 120 });
      doc.moveDown(0.8);
    });
  }

  // ── FOLLOW-UPS ──────────────────────────────────────────
  if (Array.isArray(insights.follow_ups) && insights.follow_ups.length) {
    doc.moveDown(1);
    doc.fontSize(10).fillColor(BRAND.lime).font('Helvetica-Bold').text('· RECOMMENDED FOLLOW-UPS');
    sectionDivider(doc);
    insights.follow_ups.forEach(fu => {
      doc.fontSize(12).fillColor('#ffffff').font('Helvetica-Bold').text(fu.title || '');
      doc.fontSize(10).fillColor(BRAND.text2).font('Helvetica').text(fu.rationale || '');
      doc.moveDown(0.6);
    });
  }

  // ── FOOTER on every page ────────────────────────────────
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(8).fillColor(BRAND.text3).font('Helvetica')
       .text(`VETT · vettit.ai  ·  ${i + 1} / ${range.count}`,
         50, doc.page.height - 35, {
           align: 'center', width: doc.page.width - 100,
         });
  }

  doc.end();
}

module.exports = { buildPDF };
