-- Pass 36 A0 — P0 false-advertising bug recovery.
--
-- May 11 2026: live customer demo failed because every paid mission
-- overstated respondent count by 2-10x. Pass 33 W4 backfill counted
-- mission_responses ROWS (personas × questions) instead of distinct
-- personas. The Pass 33 W4 verification SQL was tautological — it
-- compared the lying column to its own derivation and always returned
-- 0 broken.
--
-- Doctrine #16 (added this pass): SQL invariants must compare to
-- GROUND TRUTH not derived columns. delivered_respondent_count must
-- compare to COUNT(DISTINCT persona_id), not row count.
--
-- This migration:
--   1. Recomputes delivered_respondent_count for every paid completed
--      mission using COUNT(DISTINCT persona_id) from mission_responses.
--   2. Resolves the 5 over_delivered_no_refund admin alerts that were
--      generated by the buggy count — these were never real
--      over-deliveries; the column was lying.
--   3. CA missions stay at 0 (delivery_unit='creative_asset').
--
-- Apply via apply_migration as `pass_36_a0_delivered_count_backfill`.

UPDATE missions m
SET delivered_respondent_count = sub.actual_personas
FROM (
  SELECT mr.mission_id, COUNT(DISTINCT mr.persona_id)::int AS actual_personas
  FROM mission_responses mr
  GROUP BY mr.mission_id
) AS sub
WHERE m.id = sub.mission_id
  AND m.paid_at IS NOT NULL
  AND m.status = 'completed'
  AND m.goal_type != 'creative_attention'
  AND m.delivered_respondent_count != sub.actual_personas;

-- CA missions stay at 0 (delivery_unit='creative_asset' = no respondent rows).
UPDATE missions
SET delivered_respondent_count = 0
WHERE goal_type = 'creative_attention'
  AND paid_at IS NOT NULL
  AND status = 'completed'
  AND delivered_respondent_count != 0;

-- Resolve the false over_delivered_no_refund alerts that the buggy
-- counter generated. These were never real over-deliveries.
UPDATE admin_alerts
SET resolved = true,
    payload = COALESCE(payload, '{}'::jsonb) || jsonb_build_object(
      'pass_36_a0_resolution',
      'False alert from delivered_respondent_count row-count bug. ' ||
      'Pass 33 W4 set the column to mission_responses row count; ' ||
      'Pass 36 A0 corrected to COUNT(DISTINCT persona_id). The ' ||
      '"over-delivery" never happened.',
      'resolved_at', NOW(),
      'resolved_by_pass', 36
    )
WHERE resolved = false
  AND alert_type = 'over_delivered_no_refund';

-- Verification — must return 0 after this migration:
-- SELECT COUNT(*) FROM (
--   SELECT m.id FROM missions m
--   WHERE m.paid_at IS NOT NULL AND m.status = 'completed'
--     AND m.goal_type != 'creative_attention'
--     AND m.delivered_respondent_count != (
--       SELECT COUNT(DISTINCT persona_id) FROM mission_responses mr
--       WHERE mr.mission_id = m.id
--     )
-- ) s;
